<a href="https://colab.research.google.com/github/Aditya2086/Python-Training/blob/main/Day_11_PT_03_Numpy_Numeric_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy
a = numpy.array([1,2,3,4,5,6,7,8,9])
print(a)
print(a.size)
print(a.shape)
print(type(a))

[1 2 3 4 5 6 7 8 9]
9
(9,)
<class 'numpy.ndarray'>


In [2]:
a = numpy.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
print(a.size)
print(a.shape)
print(type(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)
<class 'numpy.ndarray'>


In [3]:
a = numpy.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
a = numpy.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a.itemsize) # gives the size of element in bytes

8


In [5]:
a = numpy.array([(1,2,3),(4,5,6)])
print('Before Reshaping:')
print(a)
print('The dimensions are:', a.shape)
a = a.reshape(3,2)
print('After Reshaping:')
print(a)
print('The dimensions are:', a.shape)

Before Reshaping:
[[1 2 3]
 [4 5 6]]
The dimensions are: (2, 3)
After Reshaping:
[[1 2]
 [3 4]
 [5 6]]
The dimensions are: (3, 2)


In [6]:
import numpy as np
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
a = np.arange(6).reshape(2,3) # another way to write matrix
print(a)

[[0 1 2]
 [3 4 5]]


In [8]:
from numpy import array
a = array([(1,2,3),(4,5,6),(7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
a = np.arange(6).reshape(3,3) # another way to write matrix
print(a)

ValueError: ignored

In [10]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
a = np.ones((2,3))
print(a)a = np.eye(3,3)
print(a)

SyntaxError: ignored

In [15]:
a = np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
a = np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [17]:
a = np.array([[67, 19], [39, 13]])
d = np.linalg.det(a)
print(d)

129.99999999999986


In [18]:
a = np.array([[67, 19], [39, 13]])
d = np.linalg.inv(a)
print(d)

[[ 0.1        -0.14615385]
 [-0.3         0.51538462]]


# **If an array has a very small or very large determinant, then a call to det may overflow or underflow.**

# **numpy.linalg.slogdet is more robust against such issues, because it computes the logarithm of the determinant rather than the determinant itself.**

In [19]:
a = np.array([[67, 19], [39, 13]])
(sign, logdet) = np.linalg.slogdet(a)
print(sign, logdet)
d = sign * np.exp(logdet)
print(d)

1.0 4.867534450455581
129.99999999999986


# **Most Important Concept To Be Used in ML :-**

In [20]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a.sum(axis = 0))

[12 15 18]


In [21]:
print(a.sum(axis = 1))

[ 6 15 24]


# **Flattening Arrays :-**

In [22]:
a = np.array([[0,1], [2,3]])
b = a.flatten()
print(b)
b[0] = 10
print('The array b is:',b)
print('The array a is:',a)

[0 1 2 3]
The array b is: [10  1  2  3]
The array a is: [[0 1]
 [2 3]]


In [23]:
a = np.array([[0,1], [2,3]])
b = a.ravel()
print(b)
b[0] = 10
print('The array b is:',b)
print('The array a is:',a)

[0 1 2 3]
The array b is: [10  1  2  3]
The array a is: [[10  1]
 [ 2  3]]


# **Some Important Operations :-**

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a - b)

[-3 -3 -3]


In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a * b)

[ 4 10 18]


In [27]:
a = np.array([np.arange(0,3), np.arange(0,6)])
b = np.array([np.arange(0,2), np.arange(2,4), np.arange(4,6)])
print('Matrix a is:',a)
print('Matrix b is:',b)
print('Scalar Product is:', a * 2)
print('Dot Product:', np.dot(a, b))

Matrix a is: [array([0, 1, 2]) array([0, 1, 2, 3, 4, 5])]
Matrix b is: [[0 1]
 [2 3]
 [4 5]]
Scalar Product is: [array([0, 2, 4]) array([ 0,  2,  4,  6,  8, 10])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


ValueError: ignored

In [28]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
print(a + b)

ValueError: ignored

# **Broadcast :-**

In [29]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
b = np.array([1,2,3])
c = np.array([10, 20])
print(a.shape, b.shape, c.shape)
print(a + c)

[[1 2]
 [3 4]
 [5 6]]
(3, 2) (3,) (2,)
[[11 22]
 [13 24]
 [15 26]]


In [30]:
print(a + b)

ValueError: ignored

# **1. Size Of Each Dimensions Should Be Same**
# **2. Size Of One Of The Dimension Should Be 1**

# **Numeric Python 2 :-**

In [31]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9]) # creates a 1-D array
print("Array :",arr)
print("Array Size :",arr.size)
print("Array Dimensions :",arr.shape)
print("Array type :",type(arr))

Array : [1 2 3 4 5 6 7 8 9]
Array Size : 9
Array Dimensions : (9,)
Array type : <class 'numpy.ndarray'>


In [32]:
arr1 = np.array([(1,2,3),(4,5,6),(7,8,9)]) # creates a 2-D Array
print("Array :",arr1)
print("Array Size :",arr1.size)
print("Array Dimensions :",arr1.shape)
print("Array type :",type(arr1))

Array : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array Size : 9
Array Dimensions : (3, 3)
Array type : <class 'numpy.ndarray'>


In [33]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3) # converts 1-D array to passes "n X m" dimensional 2-D array
print("Array :",arr2)

Array : [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print("Size of Elements in Bytes :",arr2.itemsize) # gives size of elements in bytes

Size of Elements in Bytes : 8


In [35]:
# changing the dimensions of the existing array using "reshape()" method.
x = np.array([(54,35,75,97),(15,67,15,14)])
print("Before Reshaping.....")
print("Array :",x)
x = x.reshape(4,2)
print("Before Reshaping.....")
print("Array :",x)

Before Reshaping.....
Array : [[54 35 75 97]
 [15 67 15 14]]
Before Reshaping.....
Array : [[54 35]
 [75 97]
 [15 67]
 [15 14]]


In [36]:
x = np.arange(10).reshape(5,2) # another way to write matrix
print("array :",x) # <row> , <col>

array : [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [37]:
# array having less or more than passed dimensions will not be reshaped.
x = np.arange(10).reshape(3,2) # another way to write matrix
print("array :",x) # <row> , <col>

ValueError: ignored

In [38]:
p = np.zeros((2,3)) # a Matrix Filled with all elements zero
print("Matrix :",p)

Matrix : [[0. 0. 0.]
 [0. 0. 0.]]


In [39]:
p = np.ones((2,3)) # a Matrix Filled with all elements zero
print("Matrix :",p)

Matrix : [[1. 1. 1.]
 [1. 1. 1.]]


In [40]:
p = np.eye(2,2) # creates an Identity matrix of "N X N" dimension
print("Matrix :",p)

Matrix : [[1. 0.]
 [0. 1.]]


In [41]:
p = np.diag([1,2,3]) # creates a diagonal matrix
print("Matrix :",p)

Matrix : [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [42]:
m = np.array([[54,44],[61,35]])
det = np.linalg.det(m) # finds determinant of a matrix
print("Determinant Value =",det)

Determinant Value = -794.0000000000003


In [43]:
m = np.array([[54,44],[61,35]])
det = np.linalg.inv(m) # finds inverse of a matrix
print("Inverse Value =",det)

Inverse Value = [[-0.0440806   0.05541562]
 [ 0.0768262  -0.06801008]]


In [44]:
m = np.array([[54,44],[61,35]])
(sign,lodget) = np.linalg.slogdet(m)
print(sign,lodget)
det = np.linalg.det(m) 
print("Determinant Value =",det)

-1.0 6.677083461247136
Determinant Value = -794.0000000000003


In [45]:
m = np.array([[8,4,3],[9,1,6],[2,7,4]])
print(m.sum(axis=1)) # Adding elements row-wise

[15 16 13]


In [46]:
print(m.sum(axis=0)) # Adding elements column-wise

[19 12 13]


In [47]:
# flattening arrays
x = np.array([[0,1],[2,3]])
y = x.flatten()
print(y)
y[0] = 10
print("Array 2 is :",y)
print("Array 1 is :",x)

[0 1 2 3]
Array 2 is : [10  1  2  3]
Array 1 is : [[0 1]
 [2 3]]


In [48]:
x = np.array([[0,1],[2,3]])
y = x.ravel()
print(y)
y[0] = 10
print("Array 2 is :",y)
print("Array 1 is :",x)

[0 1 2 3]
Array 2 is : [10  1  2  3]
Array 1 is : [[10  1]
 [ 2  3]]


In [49]:
x = np.array([4,5,6])
y = np.array([7,8,9])
print("Addition :",x + y)

Addition : [11 13 15]


In [50]:
x = np.array([4,5,6])
y = np.array([7,8,9])
print("Subtraction :",x - y)

Subtraction : [-3 -3 -3]


In [51]:
x = np.array([4,5,6])
y = np.array([7,8,9])
print("Multiplication :",x * y)

Multiplication : [28 40 54]


In [52]:
x = np.array([14,15,16])
y = np.array([7,8,9])
print("Integer Division :",x // y)

Integer Division : [2 1 1]


In [53]:
# Scalar Product not possible for different dimensional arrays.
a = np.array([np.arange(0,3), np.arange(0,6)])
b = np.array([np.arange(0,2), np.arange(2,4), np.arange(4,6)])
print('Matrix a is:',a)
print('Matrix b is:',b)
print('Scalar Product is:', a * 2)
print('Dot Product:', np.dot(a, b))

Matrix a is: [array([0, 1, 2]) array([0, 1, 2, 3, 4, 5])]
Matrix b is: [[0 1]
 [2 3]
 [4 5]]
Scalar Product is: [array([0, 2, 4]) array([ 0,  2,  4,  6,  8, 10])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


ValueError: ignored

In [54]:
# Addition of two arrays having different dimensions is not possible.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
print("Sum =",a + b)

ValueError: ignored

In [55]:
x = np.array([[45,65],[74,34],[31,19]])
print("Matrix 1 :",x)
y = np.array([37,25,85])
z = np.array([34,24])
print("shape of x :",x.shape)
print("shape of y :",y.shape)
print("shape of z :",z.shape)
print("Addition of x and z :",x + z)

Matrix 1 : [[45 65]
 [74 34]
 [31 19]]
shape of x : (3, 2)
shape of y : (3,)
shape of z : (2,)
Addition of x and z : [[ 79  89]
 [108  58]
 [ 65  43]]


In [56]:
print(x + y)

ValueError: ignored