<a href="https://colab.research.google.com/github/Aditya2086/Python-Training/blob/main/Day_11_PT_02_Destructor%2C_Inheritance%2C_Abstraction_and_Methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Destructors in OOPS :-**

In [1]:
class demo:
  def __init__(self):
    print('Constructor is called')

  def display(self):
    print('Display method is called')

  def __del__(self):
    print('Destructor is called')

d = demo()
d.display()

Constructor is called
Display method is called


# **How To Change Private Attributes :-**

In [2]:
class speed:
  def __init__(self):
    self.speed = 10

  def get_speed(self):
    return self.speed

s = speed()
s.get_speed()

10

In [3]:
class speed:
  def __init__(self):
    self.speed = 10

  def get_speed(self):
    return self.speed

s = speed()
s.speed = 100
s.get_speed()

100

In [4]:
class speed:
  def __init__(self):
    self.speed = 10
    self.__setspeed = 70

  def get_speed(self):
    return self.speed

  def set_speed(self):
    return self.__setspeed

s = speed()
s.speed = 100
s.__setspeed = 120
s.get_speed(), s.set_speed()

(100, 70)

In [5]:
class speed:
  def __init__(self):
    self.speed = 10
    self.__setspeed = 70

  def get_speed(self):
    return self.speed

  def set_speed(self):
    return self.__setspeed

  def set_speed_limit(self, new_speed):
    self.__setspeed = new_speed

s = speed()
s.speed = 100
s.set_speed_limit(120)
s.get_speed(), s.set_speed()

(100, 120)

# **Abstraction in OOPS Python :-**

In [6]:
from abc import ABC, abstractmethod
class animal(ABC):
  @abstractmethod
  def dog(self):
    pass # declared but not defined

class pet(animal):
  def dog(self):
    print('Loyal friend')

p = pet()
p.dog()

Loyal friend


# **Inheritance :-**

In [7]:
class employee:
  raise_amount = 1.05
  def __init__(self, firstn, lastn, sal):
    self.firstn = firstn
    self.lastn = lastn
    self.sal = sal

  def fulln(self):
    return '{} {}'.format(self.firstn, self.lastn)

  def raise_in_salary(self):
    self.sal = int(self.sal * self.raise_amount)

emp1 = employee('Tony', 'Stark', 75000000)
emp2 = employee('Steve', 'Rogers', 65000000)
print(emp1.fulln())
print('The salary is', emp1.sal)
emp1.raise_in_salary()
print('The salary is', emp1.sal)

Tony Stark
The salary is 75000000
The salary is 78750000


In [8]:
class developers(employee):
  pass

emp1 = developers('Tony', 'Stark', 75000000)
emp2 = developers('Steve', 'Rogers', 65000000)
print(emp1.fulln())
print('The salary is', emp1.sal)
emp1.raise_in_salary()
print('The salary is', emp1.sal)

Tony Stark
The salary is 75000000
The salary is 78750000


In [9]:
class developers(employee):
  raise_amount = 2.04

emp1 = developers('Tony', 'Stark', 75000000)
emp2 = developers('Steve', 'Rogers', 65000000)
print(emp1.fulln())
print('The salary is', emp1.sal)
emp1.raise_in_salary()
print('The salary is', emp1.sal)

Tony Stark
The salary is 75000000
The salary is 153000000


In [10]:
class developers(employee):
  raise_amount = 2.04
  def __init__(self, firstn, lastn, sal, prog_lang):
    employee.__init__(self, firstn, lastn, sal)
    self.prog_lang = prog_lang

emp1 = developers('Tony', 'Stark', 75000000, 'Python')
emp2 = developers('Steve', 'Rogers', 65000000, 'Javascript')
print(emp1.fulln())
print('The salary is', emp1.sal)
emp1.raise_in_salary()
print('The salary is', emp1.sal)

Tony Stark
The salary is 75000000
The salary is 153000000


In [11]:
class developers(employee):
  raise_amount = 2.04
  def __init__(self, firstn, lastn, sal, prog_lang):
    super().__init__(firstn, lastn, sal)
    self.prog_lang = prog_lang

emp1 = developers('Tony', 'Stark', 75000000, 'Python')
emp2 = developers('Steve', 'Rogers', 65000000, 'Javascript')
print(emp1.fulln())
print('The salary is', emp1.sal)
emp1.raise_in_salary()
print('The salary is', emp1.sal)

Tony Stark
The salary is 75000000
The salary is 153000000


In [12]:
class managers(employee):
  def __init__(self, firstn, lastn, sal, employees = None):
    super().__init__(firstn, lastn, sal)
    if employees is None:
      self.employees = []
    else:
      self.employees = employees

  def add_emp(self,emp):
    if emp not in self.employees:
      self.employees.append(emp)
  
  def remove_emp(self, emp):
    if emp in self.employees:
      self.employees.remove(emp)

  def print_emp(self):
    for emp in self.employees:
      print('-->',emp.fulln())

emp1 = developers('Tony', 'Stark', 75000000, 'Python')
emp2 = developers('Steve', 'Rogers', 65000000, 'Javascript')
mgr = managers('Nick', 'Fury', 1000000000, [emp1])
print(mgr.sal)
mgr.add_emp(emp2)
print('Employees List After adding all employees:')
mgr.print_emp()
mgr.remove_emp(emp1)
print('Employees List After removing any employees:')
mgr.print_emp()

1000000000
Employees List After adding all employees:
--> Tony Stark
--> Steve Rogers
Employees List After removing any employees:
--> Steve Rogers


In [13]:
def add_emp(emp, emp_list = []):
  emp_list.append(emp)
  print(emp_list)

emp_list = ['Tony', 'Steve']
add_emp('Bruce')
add_emp('Thor')
add_emp('Strange')
print(emp_list)

['Bruce']
['Bruce', 'Thor']
['Bruce', 'Thor', 'Strange']
['Tony', 'Steve']


In [14]:
def add_emp(emp, emp_list = None):
  if emp_list is None:
    emp_list = []
  emp_list.append(emp)
  print(emp_list)

emp_list = ['Tony', 'Steve']
add_emp('Bruce')
add_emp('Thor')
add_emp('Strange')
print(emp_list)

['Bruce']
['Thor']
['Strange']
['Tony', 'Steve']


# **Repr, Str Methods :-**

In [15]:
class employee:
  raise_amount = 1.05
  def __init__(self, firstn, lastn, sal):
    self.firstn = firstn
    self.lastn = lastn
    self.sal = sal

  def fulln(self):
    return '{} {}'.format(self.firstn, self.lastn)

  def raise_in_salary(self):
    self.sal = int(self.sal * self.raise_amount)

  def __repr__(self):
    return '{} {}'.format(self.firstn, self.lastn)

  def __str__(self):
    return '{}- {}'.format(self.fulln(), self.sal)

emp1 = employee('Tony', 'Stark', 75000000)
emp2 = employee('Steve', 'Rogers', 65000000)
print(emp1)

Tony Stark- 75000000


# **Different methods in OOPS :-**

In [16]:
class MyClass:
  def method(self):
    return 'Instance Method Called', self

  @classmethod
  def class_method(cls):
    return 'Class Method Called', cls

  @staticmethod
  def static_method():
    return 'Static Method Called'

obj = MyClass()
obj.method()

('Instance Method Called', <__main__.MyClass at 0x7fd2e414b410>)

In [17]:
class Pizza:
  def __init__(self, ingredients):
    self.ingredients = ingredients

  def __repr__(self):
    return f'Pizza({self.ingredients})'

  @classmethod 
  def __panpizza__(cls, self):
    self.type = type 
  
  def pizzatype(self, types):
    return types

  @classmethod
  def bakepizza(cls):
    return cls(['mozzarella', 'cheeseburst', 'onion'])

p = Pizza('Heese Burst Pizza')
t = Pizza('Pan Pizza')
print(t.pizzatype('Pan Pizza'))

Pan Pizza


In [18]:
import math
class Pizza:
  def __init__(self, radius, ingredients):
    self.radius = radius
    self.ingredients = ingredients

  def area(self):
    return self.pizza_area(self.radius)
  
  @staticmethod
  def pizza_area(r):
    return math.pi*r**2

p = Pizza(4,['Barbequed', 'Pan'])
print(p.area())

50.26548245743669


In [19]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9]) # creates a 1-D array
print("Array :",arr)
print("Array Size :",arr.size)
print("Array Dimensions :",arr.shape)
print("Array type :",type(arr))

Array : [1 2 3 4 5 6 7 8 9]
Array Size : 9
Array Dimensions : (9,)
Array type : <class 'numpy.ndarray'>


In [20]:
arr1 = np.array([(1,2,3),(4,5,6),(7,8,9)]) # creates a 2-D Array
print("Array :",arr1)
print("Array Size :",arr1.size)
print("Array Dimensions :",arr1.shape)
print("Array type :",type(arr1))

Array : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array Size : 9
Array Dimensions : (3, 3)
Array type : <class 'numpy.ndarray'>


In [21]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3) # converts 1-D array to passes "n X m" dimensional 2-D array
print("Array :",arr2)

Array : [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print("Size of Elements in Bytes :",arr2.itemsize) # gives size of elements in bytes

Size of Elements in Bytes : 8


In [23]:
# changing the dimensions of the existing array using "reshape()" method.
x = np.array([(54,35,75,97),(15,67,15,14)])
print("Before Reshaping.....")
print("Array :",x)
x = x.reshape(4,2)
print("Before Reshaping.....")
print("Array :",x)

Before Reshaping.....
Array : [[54 35 75 97]
 [15 67 15 14]]
Before Reshaping.....
Array : [[54 35]
 [75 97]
 [15 67]
 [15 14]]


In [24]:
x = np.arange(10).reshape(5,2) # another way to write matrix
print("array :",x) # <row> , <col>

array : [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [25]:
# array having less or more than passed dimensions will not be reshaped.
x = np.arange(10).reshape(3,2) # another way to write matrix
print("array :",x) # <row> , <col>

ValueError: ignored

In [26]:
p = np.zeros((2,3)) # a Matrix Filled with all elements zero
print("Matrix :",p)

Matrix : [[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
p = np.ones((2,3)) # a Matrix Filled with all elements zero
print("Matrix :",p)

Matrix : [[1. 1. 1.]
 [1. 1. 1.]]


In [28]:
p = np.eye(2,2) # creates an Identity matrix of "N X N" dimension
print("Matrix :",p)

Matrix : [[1. 0.]
 [0. 1.]]


In [29]:
p = np.diag([1,2,3]) # creates a diagonal matrix
print("Matrix :",p)

Matrix : [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [30]:
m = np.array([[54,44],[61,35]])
det = np.linalg.det(m) # finds determinant of a matrix
print("Determinant Value =",det)

Determinant Value = -794.0000000000003


In [31]:
m = np.array([[54,44],[61,35]])
det = np.linalg.inv(m) # finds inverse of a matrix
print("Inverse Value =",det)

Inverse Value = [[-0.0440806   0.05541562]
 [ 0.0768262  -0.06801008]]


In [32]:
m = np.array([[54,44],[61,35]])
(sign,lodget) = np.linalg.slogdet(m)
print(sign,lodget)
det = np.linalg.det(m) 
print("Determinant Value =",det)

-1.0 6.677083461247136
Determinant Value = -794.0000000000003


In [33]:
m = np.array([[8,4,3],[9,1,6],[2,7,4]])
print(m.sum(axis=1)) # Adding elements row-wise

[15 16 13]


In [34]:
print(m.sum(axis=0)) # Adding elements column-wise

[19 12 13]


In [35]:
# flattening arrays
x = np.array([[0,1],[2,3]])
y = x.flatten()
print(y)
y[0] = 10
print("Array 2 is :",y)
print("Array 1 is :",x)

[0 1 2 3]
Array 2 is : [10  1  2  3]
Array 1 is : [[0 1]
 [2 3]]


In [36]:
x = np.array([[0,1],[2,3]])
y = x.ravel()
print(y)
y[0] = 10
print("Array 2 is :",y)
print("Array 1 is :",x)

[0 1 2 3]
Array 2 is : [10  1  2  3]
Array 1 is : [[10  1]
 [ 2  3]]


In [37]:
x = np.array([4,5,6])
y = np.array([7,8,9])
print("Addition :",x + y)

Addition : [11 13 15]


In [38]:
x = np.array([4,5,6])
y = np.array([7,8,9])
print("Subtraction :",x - y)

Subtraction : [-3 -3 -3]


In [39]:
x = np.array([4,5,6])
y = np.array([7,8,9])
print("Multiplication :",x * y)

Multiplication : [28 40 54]


In [40]:
x = np.array([14,15,16])
y = np.array([7,8,9])
print("Integer Division :",x // y)

Integer Division : [2 1 1]


In [41]:
# Scalar Product not possible for different dimensional arrays.
a = np.array([np.arange(0,3), np.arange(0,6)])
b = np.array([np.arange(0,2), np.arange(2,4), np.arange(4,6)])
print('Matrix a is:',a)
print('Matrix b is:',b)
print('Scalar Product is:', a * 2)
print('Dot Product:', np.dot(a, b))

Matrix a is: [array([0, 1, 2]) array([0, 1, 2, 3, 4, 5])]
Matrix b is: [[0 1]
 [2 3]
 [4 5]]
Scalar Product is: [array([0, 2, 4]) array([ 0,  2,  4,  6,  8, 10])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


ValueError: ignored

In [42]:
# Addition of two arrays having different dimensions is not possible.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
print("Sum =",a + b)

ValueError: ignored

In [43]:
x = np.array([[45,65],[74,34],[31,19]])
print("Matrix 1 :",x)
y = np.array([37,25,85])
z = np.array([34,24])
print("shape of x :",x.shape)
print("shape of y :",y.shape)
print("shape of z :",z.shape)
print("Addition of x and z :",x + z)

Matrix 1 : [[45 65]
 [74 34]
 [31 19]]
shape of x : (3, 2)
shape of y : (3,)
shape of z : (2,)
Addition of x and z : [[ 79  89]
 [108  58]
 [ 65  43]]


In [44]:
print(x + y)

ValueError: ignored